---
- hosts: all
  tasks:
  - name: Get Server Uptime
    shell: uptime
    register: uptime

  - debug: var={{item}}
    with_items:
     - uptime.stdout
     
  - name: Disk usage from command module
    command: df -h
    register: space
  - debug:
          var: space.stdout_lines
